### ISSUE TITLE
Fix for "can't rename byte as 'xxx' because the name is already used in the program."

### ISSUE THREAD

**Issue by BigJim** [you0708/ida#7]
In IDA labels/names must be unique (unlike Ghidra).
If you try to use the same name again you will get a dialog box and a message like:  
> can't rename byte as 'CRC32_m_tab_le' because the name is already used in the program.

The easy fix is to change line #39 from "idc.set_name(ea, const["name"])" to "idc.set_name(ea, const["name"], ida_name.SN_FORCE)".  
The "SN_FORCE" flag will automatically serialize the name for you.  So the naming sequence in this example will be "ms_pst_crc32_table", "ms_pst_crc32_table_1", "ms_pst_crc32_table_2", and so on.

P.S. Also check out this plugin. It's not as easy as Python but it might have some patterns this one doesn't:  
https://sourceforge.net/projects/idasignsrch/

**Comment by you0708** [comment]
Fixed. Thank you for reporting!
